### ISSUE TITLE
postwoman测试本地接口

### ISSUE THREAD

**Issue by valtenhyl** [marsvet/uTools-plugins#1]
要想测试本地开发的接口怎么设置呢，只能用 `https://httpbin.org/get` 这个网址吗

**Comment by marsvet** [comment]
不好意思，这么久才看到。我也不太会用postwoman，除了`https://httpbin.org/get`这个网址之外其他都是`Network Error`，我只是把它搬过来了，这是postwoman的仓库地址：`https://github.com/liyasthomas/postwoman`
