### ISSUE TITLE
打开程序有问题

### ISSUE THREAD

**Issue by xluos** [marsvet/uTools-plugins#3]
![image](https://user-images.githubusercontent.com/23625189/87904667-60200000-ca91-11ea-9ff2-4115b9ef41ee.png)
软件路径配置的是正确的，上周使用时还是正常的，这周使用的时候选webstorm的项目总是用idea打开

**Comment by marsvet** [comment]
是更新到0.1.2以后才有的问题吗，还是0.1.1就有这个问题？
清空数据重新配置下试试

**Comment by xluos** [comment]
@marsvet 应该是升到0.1.2的问题，我记得昨天用的时候又弹了一次第一次安装时的弹窗，后面就有问题了。
刚刚试了一下清数据和重装，webstorm和idea都用不了了，会弹提示“不是有效的可执行程序”

**Comment by azhuang321** [comment]
我也是同样的问题  一模一样， 同样是配置正确显示“不是有效的可执行程序”

**Comment by marsvet** [comment]
@xluos @azhuang321 我改了下，应该没问题了，已经发布，正在等官方审核

**Comment by xluos** [comment]
更新后我这里没问题了

**Comment by azhuang321** [comment]
感谢
