### ISSUE TITLE
JetBrains History mac文件位置

### ISSUE THREAD

**Issue by yhan219** [marsvet/uTools-plugins#4]
详细介绍里面缺少了mac配置。

以idea为例
## `recentProject.xml`位置
`/Users/用户名/Library/Application Support/JetBrains/IntelliJIdea版本号/options/recentProjects.xml`
例如我的：
`/Users/yhan219/Library/Application Support/JetBrains/IntelliJIdea2020.2/options/recentProjects.xml`
## 可执行程序路径
`/Applications/IntelliJ IDEA.app/Contents/MacOS/idea`

**Comment by marsvet** [comment]
@yhan219 感谢感谢，下个版本会加上去
