### ISSUE TITLE
怎么取消配置

### ISSUE THREAD

**Issue by ayuayue** [marsvet/uTools-plugins#6]
配置错了,怎么清空配置
还有 `goland` 的 `recentProject.xml` 老是报路径问题,路径是正确的

**Comment by marsvet** [comment]
暂时只能清除数据重新配置，以后有时间会做个配置页面，这段时间比较忙。goland版本多少，啥系统，有没有其他IDE，有的话其他IDE有没有问题

**Comment by ayuayue** [comment]
`goland 2020-02` `win10`家庭版,我错误的配置了`interlij `,所以我想重新配置可执行程序目录,进到`utools`中目录删除了扩展重新安装发现数据没有清空

**Comment by ayuayue** [comment]
发现无法直接拖文件进去设置,刚刚重新直接拖到了`utools`的窗口里,配置了路径,可以了.但是其他配置错的想要清空却不知道怎么清空,现在我是给`intellij`也配置的`goland`的路径,因为无法清空.
可以加一个选择`ide`,好多`ide`一个人可能不会同时使用.

**Comment by ayuayue** [comment]
怎么清除数据,是插件的数据还是`utools`的数据,如果是`utools`的数据那就算了

**Comment by marsvet** [comment]
> 怎么清除数据,是插件的数据还是`utools`的数据,如果是`utools`的数据那就算了

可以在帐号与数据里清空单个插件的数据
![image](https://user-images.githubusercontent.com/36563356/91993167-a1315280-ed67-11ea-9973-95ba2fcda096.png)

**Comment by ayuayue** [comment]
谢谢
